app_name = "magic_make_up"

log_level = "DEBUG"

avatars_dir = "./avatars/"

[mysql]
ip = "127.0.0.1"
port = "3306"
user = "root"
password = "xqt19980901"
database = "magic_make_up"

[redis]
ip = "127.0.0.1"
port = "6379"

[server]
ip = "127.0.0.1"
port = "8888"
