app_name = "magic_make_up"

log_level = "DEBUG"

avatars_dir = "./avatars/"
star_imgs_dir = "./stars/"

[mysql]
ip = "127.0.0.1"
port = "3306"
user = "root"
password = "123456"
database = "magic_make_up"

[redis]
ip = "127.0.0.1"
port = "6379"

[server]
ip = "127.0.0.1"
port = "8888"

[rabbitmq]
ip = "127.0.0.1"
port = "5672"
user = "xingqingtao"
password = "123456"
vhost = "magic_make_up"
comment_queue = "commentQueue"
